# Generated by Django 4.1.5 on 2023-01-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0010_remove_dweet_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
    ]
